version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=golangisfun
      - MYSQL_DATABASE=go-practice
      - MYSQL_USER=gousr
      - MYSQL_PASSWORD=gopass
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local